apiVersion: apps/v1
kind: Deployment
metadata:
  name: invader3
  labels:
    role: app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
        - name: app
          image: imzacm/invader3:a2f847242dff6b328cbd4199719dcb5278264817
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              value: "8080"
