name: Docker
on:
  push:
    branches:
      - master
jobs:
  docker:
    name: Build, tag, and push docker image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true

      - name: Build and push docker image
        run: |
          docker build . -t invader3:${GITHUB_SHA} -t invader3:latest
          docker push invader3:${GITHUB_SHA}
          docker push invader3:latest
